# Bag of Words

In [2]:
import numpy
import re
from nltk.corpus import stopwords
set(stopwords.words('english'))
def word_extract(sentence):
    ignore = ['a', "the", "is"]
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in ignore]
    return cleaned_text

def tokenize(sentences): 
    words = [] 
    for sentence in sentences:
        w = word_extract(sentence)    
        words.extend(w)  
        words = sorted(list(set(words))) 
        return words
    
def BOW(allsentences):
    vocab = tokenize(allsentences)
    print("Word List for Document \n{0} \n".format(vocab));
    for sentence in allsentences:
        words = word_extract(sentence)
        bag_vector = numpy.zeros(len(vocab))
        for w in words:
            for i,word in enumerate(vocab):
                if word == w: 
                    bag_vector[i] += 1 
                    print("{0}\n{1}\n".format(sentence,numpy.array(bag_vector)))

file = ["Hy! I am Javeria Hassan . ", "I am doing BSCS . ", "In which Field you are ?",
                "The most interesting subjects in BSCS are :",
                "Artificial Inteeligence , Machine Learning and Deep Learning ."]
BOW(file)

Word List for Document 
['am', 'hassan', 'hy', 'i', 'javeria'] 

Hy! I am Javeria Hassan . 
[0. 0. 1. 0. 0.]

Hy! I am Javeria Hassan . 
[0. 0. 1. 1. 0.]

Hy! I am Javeria Hassan . 
[1. 0. 1. 1. 0.]

Hy! I am Javeria Hassan . 
[1. 0. 1. 1. 1.]

Hy! I am Javeria Hassan . 
[1. 1. 1. 1. 1.]

I am doing BSCS . 
[0. 0. 0. 1. 0.]

I am doing BSCS . 
[1. 0. 0. 1. 0.]



# COSINE SIMILARITY

In [3]:
import numpy as np

def cos_sim(a, b):
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_product / (norm_a * norm_b)


sentence_A = np.array([1,2,3,4,5]) 
sentence_B = np.array([3,4,5,7,4])
sentence_C = np.array([1,2,7,8,9])


print(cos_sim(sentence_A, sentence_B)) 
print(cos_sim(sentence_A, sentence_C)) 

0.9304680279236586
0.9845308784939586
