In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import multilabel_confusion_matrix

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

In [2]:
Data=pd.read_csv("Cancer_dataset.csv")
Data.head()
feature_names=Data.columns.drop('Class')
target_names=[1,2,3,4,5]
print(feature_names)

Index(['gene_1', 'gene_2', 'gene_3', 'gene_4', 'gene_6', 'gene_7', 'gene_10',
       'gene_11', 'gene_12', 'gene_13', 'gene_14', 'gene_17', 'gene_18',
       'gene_19', 'gene_20', 'gene_21', 'gene_22', 'gene_23', 'gene_24',
       'gene_25', 'gene_26', 'gene_27', 'gene_28', 'gene_29', 'gene_30',
       'gene_31', 'gene_32', 'gene_33', 'gene_34', 'gene_35', 'gene_36',
       'gene_37', 'gene_38', 'gene_39', 'gene_40', 'gene_41', 'gene_42',
       'gene_43', 'gene_44', 'gene_45', 'gene_46', 'gene_47', 'gene_48',
       'gene_49'],
      dtype='object')


In [3]:
InputTrain = Data.drop('Class',axis="columns")
InputTarget=Data['Class']

In [4]:
X_train, X_test, y_train, y_test =train_test_split(InputTrain, InputTarget, test_size=0.3) 

In [5]:
model=tree.DecisionTreeClassifier(criterion='entropy')
model.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [6]:
DT_predict=model.predict(X_test)
acc_DT=accuracy_score(y_test,DT_predict)
acc_DT=round(acc_DT*100,2)
print(f'Accuracy of Decision Tree : {acc_DT}%')

cm=confusion_matrix(y_test,DT_predict)
print("Confusion Matrix  \n",cm)

recall = np.diag(cm) / np.sum(cm, axis = 1)
precision = np.diag(cm) / np.sum(cm, axis = 0)
print("Recall  \n",recall)
print("Precisin  \n",precision)

print("Mean Recall  \n",np.mean(recall))
print("Mean Precisin  \n",np.mean(precision))

print("Classification Report \n",classification_report(y_test,DT_predict))

Accuracy of Decision Tree : 75.21%
Confusion Matrix  
 [[20  0  0  2  1]
 [ 2 13  1  2  3]
 [ 0  0 16  1  1]
 [ 0  4  1 22  3]
 [ 0  2  0  6 17]]
Recall  
 [0.86956522 0.61904762 0.88888889 0.73333333 0.68      ]
Precisin  
 [0.90909091 0.68421053 0.88888889 0.66666667 0.68      ]
Mean Recall  
 0.7581670117322291
Mean Precisin  
 0.7657713981924508
Classification Report 
               precision    recall  f1-score   support

           1       0.91      0.87      0.89        23
           2       0.68      0.62      0.65        21
           3       0.89      0.89      0.89        18
           4       0.67      0.73      0.70        30
           5       0.68      0.68      0.68        25

    accuracy                           0.75       117
   macro avg       0.77      0.76      0.76       117
weighted avg       0.75      0.75      0.75       117

